Preparing for release.

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -5,14 +5,28 @@ definitions:
   - &code-check
     name: Performing static code analysis
     script: |
+      #!/bin/bash
+
+      ERRORS="";
+      EXIT=0;
+
       OUTPUT=$(grep -r "//String get bannerAdUnitId => BannerAd.testAdUnitId");
 
-      if  [[ ! -z "$OUTPUT" ]]; then
-        echo "Error: Test ads must be enabled in debug builds.";
-        exit 1;
+      if [[ -n "$OUTPUT" ]]; then
+          ERRORS="$ERRORS\nError: Test ads must be enabled in debug builds.";
+          EXIT=1;
       fi
 
-      exit 0;
+      OUTPUT=$(grep -r "static const timerDuration = 1;");
+
+      if [[ -n "$OUTPUT" ]]; then
+          ERRORS="$ERRORS\nError: Training timer time is in debug mode.";
+          EXIT=1;
+      fi
+
+      printf "$ERRORS";
+
+      exit $EXIT;
   - &flutter-install
     name: "Installing packages"
     script: "flutter pub get"
